theme: jekyll-theme-minimal
title: 'Advanced Single Cell RNA-Seq Workshop'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Intro to the Workshop and Core
    url: welcome
  - title: Examples of Markdown Formatting
    url: examples
